### ISSUE TITLE
plot_categorical drops overlapping loci

### ISSUE THREAD

**Issue by beausjo** [rcavalcante/annotatr#10]
The plot_categorical example in the vignette for annotating user-supplied hyper-/hypo- methylated regions as CpG island, shores, shelve, etc works as expected. But if I instead pass regions_A and regions_B and there are identical regions in both A and B then only one is reported.  For example if I want to use a bed file of individual CpGs detected in Cancer and Non-Cancer cohorts, and there is a subset of CpGs detected in both then that subset only gets reported in one of the cohorts. In this example obviously you want to count  the overlapping subset in both cohorts. 

 I traced back the data loss to this section of the ```plot_categorical``` code:

### works OK:
```
>  annotated_regions = annotatr:::subset_order_tbl(tbl = annotated_regions, col = fill, col_order = fill_order)
> table(annotated_regions$DM_status)
   Cancer NonCancer 
   100      50
```

### Non-cancer drops out entirely:

```
> annotated_regions = dplyr::distinct_(dplyr::ungroup(annotated_regions), .dots = c("seqnames", "start", "end", "annot.type"), .keep_all = TRUE)
> table(annotated_regions$DM_status)
Cancer 
100 

```
Note that in this example all of the non-cancer CpGs were also detected in cancer and as a result they were all omitted. I suppose users with disjoint sets will never run into this issue but seems like many folks will also have some overlap in their regions.

Thanks,
John

**Comment by rcavalcante** [comment]
Hi John,

Thanks for you using `annotatr`, and thanks for pointing this out. This is clearly a case where I thought  I was solving one problem and created another.

I think I have an idea of how to solve this problem. I'll try some things, and add some tests to make sure I've fixed it.

I'm currently at a conference, but I'll try to get to it by early next week.

Thanks,
Raymond

**Comment by beausjo** [comment]
Great! Thanks for developing the tool it's been  useful.

**Comment by rcavalcante** [comment]
Hi John,

I've fixed the issue in `plot_categorical()` and in `summarize_categorical()` in commit 883b3eba3267ac8912c259b81f53990eb47a89e0. So long as `x` or `fill` in `plot_categorical()` is one of the variables on which duplicate regions are unique (in your case cancer status), then the duplicate regions will be retained. Ditto for `summarize_categorical()` with the `by` parameter.

I've fixed this in the `master` branch of `annotatr`, but that relies on a `devel` version of `S4Vectors`. I've also fixed this in the `issue10` branch which is off of the `RELEASE_3_6` branch so you won't have annoying dependency problems. It's tested against the Bioconductor Release Docker image with up-to-date packages, and it appears to be fine.

You can install it with `devtools::install_github('rcavalcante/annotatr@issue10')`. If this fixes your problem after installation, please go ahead and close the issue.

Thanks!
