### ISSUE TITLE
Suggestion for read_bed()

### ISSUE THREAD

**Issue by rcavalcante** [rcavalcante/annotatr#11]
In the following statement in `read_bed()`:
```{r}
if (stranded == T & (bed[1,6] != "+" | bed[1,6] != "-")){
        stop("In read.bed(filename, genome, stranded): with stranded = T,
          strand column should contain +/- only.")
}
```
We may want to remove `(bed[1,6] != "+" | bed[1,6] != "-")` from the outer if and make an inner if like:
```{r}
if (stranded == T){
      if(bed[1,6] != "+" | bed[1,6] != "-") {
          stop("In read.bed(filename, genome, stranded): with stranded = T,
          strand column should contain +/- only.")
      }
}
```
That way users can input 3 column BED files (which are common) and not get an error for not having strand information they don't use anyway.

Let me know what you think.

**Comment by divy-kangeyan** [comment]
Hi Raymond,
                     Thank you for the clarification. Just a quick question about the genomes. Annotatr now suggests bsgenomes for `Hsapiens`, `Dmelanogaster`, `Ggallus`, `Mmusculus` and `Rnorvegicus`.  Would annotatr be able to produce annotation for other genome builds for example `Scerevisiae` even though it is not one of the suggested bsgenomes?

Thank you,
Divy

**Comment by divy-kangeyan** [comment]
I was just asking how it would handle for different species in general. I don't need `Scerevisiae` now, I was just curious how annotatr would handle different species. I think it would be great if you can add additional genome build support in the future.

Divy
