### ISSUE TITLE
Is it possible to calculate distance to nearest gene using annotatr?

### ISSUE THREAD

**Issue by bishwaG** [rcavalcante/annotatr#15]
Hi,
I have differentially methylated regions and I would like to calculate distance to nearest gene. Is there some smarter way to do using annotatr?

Regards,
bishwaG

**Comment by rcavalcante** [comment]
Hi,

Thanks for your interest in annotatr. At the moment, there is no way to do this in annotatr (though I'm starting to think that adding it would be a good idea). The `GenomicRanges` package has a `findNearest()` function which should help you get where you're going.

Raymond
