### ISSUE TITLE
Randomizing Regions

### ISSUE THREAD

**Issue by clersdom** [rcavalcante/annotatr#25]
Thanks for the package. It has been really useful!

If I have correctly understood, randomizing regions can allow comparison of how differentially methylated regions differ from other annotations. 
I have seen that in the below link there are other files available for this purpose.
https://github.com/rcavalcante/annotatr/find/master

Would you recommend any of the files available? In my case I am working with human hg19.
Thanks!
Clara

**Comment by rcavalcante** [comment]
Hi Clara,

I appreciate the feedback. Randomizing the regions can give an idea of whether differentially methylated regions (as one example) are enriched in certain annotations relative to a background set.

I would note that when randomizing regions, it's important to pay attention to the universe of the background. The function I provide (which is a wrapper for `regioneR::randomizeRegions`) only holds the number of regions per chromosome constant as well as their length distribution (good for something like ChIP-seq). But if you wanted to randomize CpGs, for example, this function would return non-CpGs, which is probably not what you want, so you should come up with your own background, not using `randomize_regions()`.

I'm not sure I entirely understand your question about the files at the link, so perhaps you can rephrase if I haven't addressed the substance of your question.

Thanks, Raymond

**Comment by clersdom** [comment]
Hi Raymond. Thank you for your fast reply. I understand your point. Then, in the case of cpgs it may not be as helpful. But as you suggest, I could use other regions that are differentially methylated to see how they compare. 

Thanks again.
Clara
