### ISSUE TITLE
Can't get this working

### ISSUE THREAD

**Issue by toates19** [rcavalcante/annotatr#3]
Hi I am having trouble running annotatr at the moment. This may reflect the fact that I have recently moved offices and am using a Windows machine and am not really used to running R in a Windows environment.
Perhaps you can help?
Thanks 
Tom

`> sessionInfo()
R version 3.3.3 (2017-03-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] BiocInstaller_1.22.3

loaded via a namespace (and not attached):
 [1] colorspace_1.3-2 scales_0.4.1     assertthat_0.1   lazyeval_0.2.0   plyr_1.8.4       tools_3.3.3      gtable_0.2.0     tibble_1.2       Rcpp_0.12.10     ggplot2_2.2.1   
[11] grid_3.3.3       munsell_0.4.3  `

**Comment by rcavalcante** [comment]
Hello,

Thanks for your interest in `annotatr`. Is the problem that you can't get `annotatr` installed on the Windows machine? Or it's otherwise behaving oddly? If it's not installing, perhaps you can convey the point at which it errors?

Thanks,
Raymond

**Comment by toates19** [comment]
Hi Raymond
Sorry for the delay, I got annotatr installed eventually. 
The problem was with the package XVector not being installed which meant that the TxDb objects which are imported by annotatr weren't installing.
Maybe you could add XVector as a dependency or an automatic import for future versions?
Thanks 
Tom

**Comment by rcavalcante** [comment]
Hello, I'm glad you got annotatr installed.

The XVector problem is a bit odd though. XVector is imported by GenomicRanges ([see here](http://bioconductor.org/packages/release/bioc/html/GenomicRanges.html)), and annotatr imports GenomicRanges, so that should be taken care of automatically.
