### ISSUE TITLE
read_regions does not work for "general" format .txt files

### ISSUE THREAD

**Issue by clersdom** [rcavalcante/annotatr#33]
Hi, 
I have a file that is saved as "General" format that I want to read and annotate. I am aware that the function `read_regions` only works for files that are saved as "text" format. 
Since the file I am trying to annotate is quite a big file, if I do this change in excel directly, when I save it, not all the data is kept in the file... 
Any help with this or anything that could solve this issue?

**Comment by rcavalcante** [comment]
Good morning,

The `read_regions()` function uses the `rtracklayer::import()` function, which requires files be BED-like (BED, bigBed, narrowPeak, broadPeak, etc). Either the extension of the file has to be BED or the `format` flag has to be used to indicate which format to use to interpret the columns.

> From rtracklayer::import(): The format of the output. If not missing, should be one of ’bed’, ’bed15’, ’bedGraph’ or ’bedpe’. If missing and ’con’ is a filename, the format is derived from the file extension. This argument is unnecessary when ’con’ is a derivative of ’RTLFile’.

Do you mind sharing a snippet of what the first few rows of your file look like? That will help us figure out how BED-like it is. Is the file `.txt` or an Excel format? Also, what operating system are you using?

Thanks for using annotatr,
Raymond
