### ISSUE TITLE
No inbuilt function to calculate percentage Overlap

### ISSUE THREAD

**Issue by Rohit-Satyam** [rcavalcante/annotatr#36]
I am using this wonderful package and it has made the annotation work much easier. However, I was presented with one issue. I have to keep only those annotations for which overlap of the intended region with the feature is at least 50 %. I am not sure the `minoverlap` subcommand has that functionality. Also, what does `minoverlap = 1 L` mean. I understand the 1 L is long-form of 1 but what does it stand for; for example, does it mean that the minimum overlap must be 1 Nucleotide or something else like a 10% overlap? What should be the value for 50% overlap in that case.

**Comment by rcavalcante** [comment]
Thanks for using annotatr. You correct, there is no way to automatically use a percentage overlap in the `annotate_regions()` function. The `minoverlap` parameter is taken from the `IRanges::findOverlaps()` function, which takes an integer and checks for a number of basepairs overlap.

You would have to write some code of your own after annotation to determine the percent overlap and then filter on that. There would be some value in adding this as a feature in the future, but I cannot promise doing that in a timely manner at the moment.

I will go ahead and close this issue.
