### ISSUE TITLE
What is the source of annotation data and can it be modified?

### ISSUE THREAD

**Issue by jpcartailler** [rcavalcante/annotatr#40]
Greetings - I'd like to be able to create a custom version of the data being used as `hg19_basicgenes`. Is that possible, and if so, how? I searched through the source and docs, but came up empty. Thanks and best regards!

**Comment by rcavalcante** [comment]
Hi, and thanks for using annotatr.

There are a couple ways you could accomplish this:

1. Use the [custom annotations](http://bioconductor.org/packages/release/bioc/vignettes/annotatr/inst/doc/annotatr-vignette.html#custom-annotations) section of the documentation to read in BED files representing what would be your custom version of `hg19_basicgenes`. You'd have to then save the `annotatr_cache` object in an `.rda` or some such to re-use it across sessions.
2. Generate `GRanges` objects that match the structure of the annotations that `annotatr` usually builds (the usual `GRanges` part but you'd have to fill in:
    * `id`, an internal annotation ID.
    * `tx_id`, a transcript identifier (ENSEMBL or UCSC or whatever you like)
    * `gene_id`, a gene level identifier (like Entrez ID)
    * `symbol`, the gene symbol
    * `type`, something of the form `[genome]_[annotation_class]_[annotation_type]`

Going with route 2 (which might be easier), you could actually co-opt the use of the `hg19_basicgenes` shortcut in downstream summary and visualization functions so long as you provided the same constituent annotations in the `type` column of the `GRanges`. That is `paste(genome, 'genes', c('1to5kb','promoters','5UTRs','exons','introns','3UTRs'), sep='_')`.

I hope that gives some idea for how you might do this.

Raymond
