### ISSUE TITLE
Request for example of Chromatin states analysis for hg38 using Annotatr

### ISSUE THREAD

**Issue by Rohit-Satyam** [rcavalcante/annotatr#41]
Hi @rcavalcante 

It would be really helpful if you could include a code chunk to demonstrate Chromatin State analysis for hg38 in your manual of annotatr. I am finding it difficult to figure out where to get the relevant files for hg38 for all the states from (for hg19 it's easy).

```r
annotatr::build_annotations(genome = 'hg38', annotations = 'hg38_Gm12878-chromatin')
Error in check_annotations(builtin_annotations) : 
  Error: "hg38_chromatin_Gm12878-ActivePromoter, hg38_chromatin_Gm12878-WeakPromoter, hg38_chromatin_Gm12878-PoisedPromoter, hg38_chromatin_Gm12878-StrongEnhancer, hg38_chromatin_Gm12878-WeakEnhancer, hg38_chromatin_Gm12878-Insulator, hg38_chromatin_Gm12878-TxnTransition, hg38_chromatin_Gm12878-TxnElongation, hg38_chromatin_Gm12878-WeakTxn, hg38_chromatin_Gm12878-Repressed, hg38_chromatin_Gm12878-Heterochrom/lo, hg38_chromatin_Gm12878-Repetitive/CNV" is(are) not supported. See builtin_annotations().
```

**Comment by rcavalcante** [comment]
Hello,

Apologies for the delay in reply over the holidays. The chromatin state analysis for hg38 is different from those of hg19, and can be found here: https://hgdownload.soe.ucsc.edu/gbdb/hg38/encode3/ccre/encodeCcreCombined.bb

I'm not sure if `rtracklayer::import` can handle bigBed files directly, so you may have to download it, convert it to BED, and then create a custom annotation to use it.

I will add this particular annotation to the list of built-ins to add to the next `annotatr` release in April.

Thanks, 
Raymond

**Comment by Rohit-Satyam** [comment]
Hi @rcavalcante 

Sorry for asking this again but have they changed from that 15 state classification as described here: https://genome.ucsc.edu/cgi-bin/hgTrackUi?db=hg19&g=wgEncodeAwgSegmentation

or am I misunderstanding something?

**Comment by rcavalcante** [comment]
Yes, they have. I wish the UCSC table browser provided static links so I could show you directly, but if you go to:

https://genome.ucsc.edu/cgi-bin/hgTables

Select hg38, the "Regulation" group, and the "ENCODE cCREs" track, you'll get an explanation.

Hope that helps!

**Comment by Rohit-Satyam** [comment]
I tried to download the file from table browser of UCSC and then split it on the basis of the cCRES category given by encode. I then made separate custom annotations for each type of cCREs as follows

```r
read_annotations(con = "pELS.txt", genome = 'hg38', name = 'pELS', format = 'bed')
read_annotations(con = "PLS.txt", genome = 'hg38', name = 'PLS', format = 'bed')
read_annotations(con = "CTCF-only.txt", genome = 'hg38', name = 'CTCF', format = 'bed')
read_annotations(con = "dELS.txt", genome = 'hg38', name = 'dELS', format = 'bed')
read_annotations(con = "DNase-H3K4me3.txt", genome = 'hg38', name = 'H3K4me3', format = 'bed')

pELS <- annotatr::build_annotations(genome = 'hg38', annotations = 'hg38_custom_pELS')
PLS <- annotatr::build_annotations(genome = 'hg38', annotations = 'hg38_custom_PLS')
CTCF <- annotatr::build_annotations(genome = 'hg38', annotations = 'hg38_custom_CTCF')
dELS <- annotatr::build_annotations(genome = 'hg38', annotations = 'hg38_custom_dELS')
H3K4me3 <- annotatr::build_annotations(genome = 'hg38', annotations = 'hg38_custom_H3K4me3')
```
All the regions that I have are 1000bp long and when I intersect with the aforementioned ranges I get an error

```r
df_anno_cpg = annotate_regions(
    regions = B,
    annotations = pELS,minoverlap = 500L,
    ignore.strand = TRUE,
    quiet = FALSE)
## where B is a GRange object that contains regions that are 1000bp long

Annotating...
Error in annotate_regions(regions = B, annotations = H3K4me3, minoverlap = 500L,  : 
  No annotations intersect the regions.
```

I went back, wrote my custom overlap script, and found that since my regions are bigger than the regions of these cCREs (which are typically in the range of 150-350 bp), I was getting zero overlaps even when the entire cCREs are contained in my 1000bp region. This raises two questions

1. This is a classic case where the regions that are being used as references are shorter than the regions under investigation. Even when the entire reference region could be contained in the region under investigation, they will be discarded. This is challenging since let's say for promoter regions, the range varies from author to author (some goes 500bp downstream from TSS and 1500bp upstream, whereas some go 2000bp upstream of TSS). How to tackle such a scenario where the reference region is contained inside the region under investigation while keeping the overlap cutoff of 50%.
2. Shouldn't this overlap be checked from both sides i.e. whether 50% of A overlaps with B or 50% of B overlaps with A and then either of the overlaps must be counted.

**Comment by rcavalcante** [comment]
Hello,

I think the issue here is the `minoverlap = 500L`. This means the overlap should be 500bp, which is 50% of your 1000bp regions, but isn't 50% overlap in the sense of the `-f` and `-F` flags in [bedtools intersect](https://bedtools.readthedocs.io/en/latest/content/tools/intersect.html#usage-and-option-summary). Here, `minoverlap` is passed **directly** to `GenomicRanges::findOverlaps()`.

So in the end, it is not possible for 150bp-350bp regions to have 500bp overlaps, and you get an empty intersection. If you want some more confidence in the intersection, perhaps `minoverlap = 75L` is a good place to start?

With that said, a proportional, and symmetrical, overlap requirement, like `bedtools intersect`, would require some implementation on my end after the original intersection. I can't promise that will happen quickly, but I don't think it would be particularly difficult. For you to do in your particular case.

Hope that helps,
Raymond
