### ISSUE TITLE
failed to load resource

### ISSUE THREAD

**Issue by mbassalbioinformatics** [rcavalcante/annotatr#42]
Hi im using annotatr v1.14 off bioconductor and when attempting to run
```
build_annotations(genome = 'hg38', annotations = "hg38_enhancers_fantom")
```

I get the following message 
```
snapshotDate(): 2020-04-27
loading from cache
Error: failed to load resource
  name: AH14150
  title: hg19ToHg38.over.chain.gz
  reason: error in evaluating the argument 'con' in selecting a method for function 'import': invalid class “ChainFile” object: undefined class for slot "resource" ("characterORconnection")
```

Im surprised this is failing since just last week on the same machine the same command worked fine.... suggestions please?

**Comment by mbassalbioinformatics** [comment]
For some reason, updating annotatr to 1.16 and rtracklayer to the latest versions fixes the problem.  The update has to be done manually though, so dl the source and install from tar.gz

**Comment by rcavalcante** [comment]
Just wanted to comment and say I'm glad you resolved the issue. 

If my memory serves, there was some breaking change to UCSC resources between versions of Bioconductor that had to be fixed (I can't remember which ones exactly, but they're likely related to the version you had and updated to). I think that might have been the issue.

Anyhow, thanks for using annotatr.
