### ISSUE TITLE
Where do the annotations come from?

### ISSUE THREAD

**Issue by ahdee** [rcavalcante/annotatr#46]
Hi, thanks for the great package.  I'm curious where the annotations/info were derived from.  I get ask this question a few times already and would be nice to know the source, thanks. 
A.

**Comment by rcavalcante** [comment]
Hi,

Thanks for using annotatr. This section of the vignette describes where the annotations come from: https://bioconductor.org/packages/release/bioc/vignettes/annotatr/inst/doc/annotatr-vignette.html#annotations.

The short answer is: TxDb/OrgDb packages, AnnotationHub resources, and direct URLs in some cases.

If you need more specificity, the package source, particularly `R/build_annotations.R`, spells out which URLs and which AnnotationHub accessions.

Hope that helps!
Raymond

**Comment by ahdee** [comment]
thanks Raymond, that is helpful.
