### ISSUE TITLE
hg38 CGI annotation

### ISSUE THREAD

**Issue by magdadrozdz** [rcavalcante/annotatr#47]
Hi, I was wondering where the data for hg38 CpG islands come from. The intro online mentions it is obtained from the AnnotationHub package, but when I looked at the available annotations there it only includes hg18, hg19 and no hg38. How did you obtain it? Did you liftover from hg19?

**Comment by rcavalcante** [comment]
Hi there,

It looks like annotatr is using UCSC, and not the AnnotationHub. This link in particular: http://hgdownload.cse.ucsc.edu/goldenpath/hg38/database/cpgIslandExt.txt.gz

Sorry, I should clarify the documentation, my mistake.

Thanks,
Raymond
