### ISSUE TITLE
Annotations for hg18?

### ISSUE THREAD

**Issue by kdkorthauer** [rcavalcante/annotatr#5]
Hi,

I see from `builtin_genomes()` that hg19 and hg38 are supported. Is there a way to retrieve annotations for other human genomes such as hg18, even though they are not "built in"? Specifically `hg18_cpgs` and `hg18_genes_cds`? 

Best,
Keegan

**Comment by rcavalcante** [comment]
Hi Keegan,

Thanks for the question, and sorry for the delay (I was traveling). Unfortunately I did not build annotations for hg18. You can, however, grab those things from the UCSC Table Browser, and use them as custom annotations.

Thanks,
Raymond
