### ISSUE TITLE
How to label individual genes of a plot_numerical ()

### ISSUE THREAD

**Issue by GitR-Bio** [rcavalcante/annotatr#53]
I would like to know how to label the individual gene names of numerical plot generated from anotatr. Please consider the following example from the user guide. Thanks in advance.

In Vignettes from package 'annotatr', 
regarding the example given in 4.5.3 Plotting Numerical Data Over Regions, 
in Figure 6: Methylation Rates in Regions Over DM Status in Group 0 vs Group 1

dm_vs_regions_name = plot_numerical(
    annotated_regions = dm_annotated,
    x = 'mu0',
    y = 'mu1',
    facet = 'annot.type',
    facet_order = c('hg19_genes_1to5kb','hg19_genes_promoters',
        'hg19_genes_5UTRs','hg19_genes_3UTRs', 'hg19_custom_ezh2',
        'hg19_genes_intergenic', 'hg19_cpg_islands', 'hg19_cpg_shores'),
    plot_title = 'Region Methylation: Group 0 vs Group 1',
    x_label = 'Group 0',
    y_label = 'Group 1')
print(dm_vs_regions_name)
![Figure 6 Plot numerical](https://github.com/rcavalcante/annotatr/assets/144215416/34adcdd6-56de-4aa8-ae1b-911879532985)

**Comment by rcavalcante** [comment]
I think something like this could get you there: https://stackoverflow.com/questions/11889625/annotating-text-on-individual-facet-in-ggplot2
