### ISSUE TITLE
Error in builtin_genomes() : could not find function "builtin_genomes"

### ISSUE THREAD

**Issue by divy-kangeyan** [rcavalcante/annotatr#7]
Hi Raymond,
                     I am building a package that imports some function from annotatr to annotate certain regions of the genome. I am using the function build_annotations to build these annotations and I am consistently getting an error saying  
`Error in builtin_genomes() : could not find function "builtin_genomes"`

I am using the current version of annotatr 1.2.1, do you have any insight on why I would get these errors.

Thank you,
Divy

**Comment by rcavalcante** [comment]
Hi Divy,

I'm flattered that you're considering importing some `annotatr` functions into your package. I just started an `R` session with `annotatr` v1.2.1 and tried a couple things:

```
?builtin_genomes
```
and
```
build_annotations(genome = 'hg19', 'hg19_basicgenes')
```
without issue. I'm wondering, could you perhaps give me an example of the code you're trying to run and I'll see if I can replicate the issue?

Thanks,
Raymond

**Comment by divy-kangeyan** [comment]
This is the the input code for the function `featureCoverage(bs,c('cpg_islands','genes_exons'),'hg38')`

featureCoverage is a simple function that summarizes the cpgs by annotation

`featureCoverage <-function(bs,features,genomebuild){

    annotationFeatures<-c()
    for (i in features){
        annotationFeatures<-c(paste0(genomebuild,'_',i),annotationFeatures)
    }


    annots_gr = annotatr::build_annotations(genome = genomebuild, annotations = annotationFeatures)

    GenomeInfoDb::seqlevelsStyle(bs)<-"UCSC"

    # CpGs that are observed
    coverageMatrix<-getCoverage(bs)
    ind<-DelayedArray::rowSums(coverageMatrix)>0

    # Intersect the regions with the reference annotations
    dm_annotated = annotatr::annotate_regions(
    regions = GenomicRanges::granges(bs)[ind,],
    annotations = annots_gr,
    ignore.strand = TRUE,
    quiet = TRUE)
    sumAnnot<-annotatr::summarize_annotations(dm_annotated,quiet=TRUE)
    sumAnnotDf<-as.data.frame(sumAnnot)
    return(sumAnnotDf)

}`

bs is a bsseq object with cpg information. 

What is interesting is that when I use `devtools::run_examples` I don't get any errors but when I use devtools::check I get the error in the step `checking examples ... ERROR` and the reason being `Error in builtin_genomes() : could not find function "builtin_genomes" `

I am not sure whether you have encountered this contradictory results from `run_examples` and `check` functions in your package development expereince?

**Comment by rcavalcante** [comment]
Hi Divy,

Thanks for the additional information. My suspicion is that the error is an issue with how `annotatr` is loaded in the `NAMESPACE` of your package. To see if that's the issue, do you mind pasting as a code block the contents of your package's `DESCRIPTION` and `NAMESPACE` files?

Thanks,
Raymond

**Comment by divy-kangeyan** [comment]
Hi Raymond,
                    This is how my `NAMESPACE` file looks like
`export(coverage)`
`export(cpgDensity)`
`export(cpgDiscretization)`
`export(createRDA)`
`export(downsample)`
`export(featureCoverage)`
`export(mbiasplot)`
`export(methylationDist)`
`export(readmetrics)`
`export(repMask)`
`export(report)`
`import(BSgenome)`
`import(GenomicRanges)`
`import(knitr)`
`importFrom(DelayedArray,colSums)`
`importFrom(DelayedArray,rowSums)`
`importFrom(GenomeInfoDb,seqlevelsStyle)`
`importFrom(annotatr,annotate_regions)`
`importFrom(annotatr,build_annotations)`
`importFrom(annotatr,builtin_genomes)`
`importFrom(annotatr,summarize_annotations)`
`importFrom(bsseq,getCoverage)`
`importFrom(stats,rbinom)`
`importFrom(stats,relevel)`

This is my `DESCRIPTION` file

`Type: Package`
`Version: 0.99.2`
`Depends: R (>= 3.4.0)`
`Imports:`
  `ggplot2,`
  `knitr,`
  `bsseq,`
  `AnnotationHub,`
  `Repitools,`
  `GenomicRanges,`
  `reshape2,`
  `stats,`
  `utils,`
  `BSgenome,`
  `DelayedArray,`
  `annotatr,`
  `SummarizedExperiment,`
  `GenomeInfoDb`
`Suggests:`
  `rmarkdown,`
  `BSgenome.Mmusculus.UCSC.mm10,`
  `BSgenome.Hsapiens.NCBI.GRCh38,`
  `Biobase,`
  `BiocGenerics,`
  `Biostrings,`
  `DT`
`License: GPL-2`
`LazyData: TRUE`
`RoxygenNote: 6.0.1`
`VignetteBuilder: knitr`


Thank you,
Divy

**Comment by rcavalcante** [comment]
Hmm, well that is curious. If you do `devtools::load_all()` in the root of your package, and then `annotatr::builtin_genomes()` do you get the error?

I haven't ever had that contradictory situation between `run_examples` and `check`. I'm curious though, what happens if you don't do this in the context of `devtools` and instead do `R CMD build` and `R CMD check`? If it works in that case, perhaps there is a `devtools` bug?

**Comment by divy-kangeyan** [comment]
Also I have to add that if I load the `annotatr` package in the example for the functions as `library(annotatr)` I no longer get the error. However since I import the package I don't think I have to explicitly load the package for the example in the preamble.

**Comment by divy-kangeyan** [comment]
Hi Raymond,
                     I will check both `R CMD build` and `R CMD check`. Just a quick question you didn't have the function `builtin_genome` in early versions of the `annotatr` package is that right?

Thank you,
Divy

**Comment by rcavalcante** [comment]
There was a function called `supported_genomes()`, but I changed it to `builtin_genomes()` because I thought the phrasing better matched its use.

**Comment by divy-kangeyan** [comment]
I tried the `R CMD check` and I was getting the same error that I got with `devtools::check`

**Comment by rcavalcante** [comment]
Hello,

I'm a little embarrassed, but I accidentally discovered the cause of the problem you reported when I tried to do the same thing. Namely, I wanted to use `annotatr` in another package, and I was getting the error you mentioned.

I have pushed an update to the `RELEASE_3_6` branch (version `1.4.1`) that should take care of this. The problem was that I should have been referring to `annotatr::builtin_genomes()` where I was referencing it. Although I thought that exporting the function would have been enough, perhaps there is a catch in certain cases.

The Bioc builds have been somewhat problematic lately because of some issues with dependency packages, so if you don't see `1.4.1` at the Bioconductor landing page (http://bioconductor.org/packages/release/bioc/html/annotatr.html), you can install the update with:
```
devtools::install_github('rcavalcante/annotatr@RELEASE_3_6')
```

Please let me know if this solves your problem. And again, I apologize for not initially understanding the problem.

Raymond

**Comment by rcavalcante** [comment]
I've also made the same patch to the `devel` version (`1.5.2`) if that's relevant to you. It can be installed with ```devtools::install_github('rcavalcante/annotatr')```

**Comment by divy-kangeyan** [comment]
Hi @rcavalcante Thank you for the update. I will try the new version
