### ISSUE TITLE
installation requires lots of other packages

### ISSUE THREAD

**Issue by nsheff** [rcavalcante/annotatr#8]
I installed `annotatr` and it downloaded many other bioconductor packages (like `TxDb.Dmelanogaster.UCSC.dm3.ensGene`, for example). I don't study flies, so this is just taking up space for me. So, a suggestion: make it so that I only have to download the annotations I am interested in, instead of sticking everything into the imports area.

**Comment by rcavalcante** [comment]
Hi, thanks for the feedback, and sorry for the delay. Using `Suggests` as indicated [here](https://www.bioconductor.org/developers/package-guidelines/#dependencies) seems to be one way forward, with an error being thrown if the required package isn't installed.

I'm playing around with using `requireNamespace()` where the `TxDb` and `OrgDb` packages are loaded, and will push to `devel` once I get the green lights on local and Travis builds.

If you know offhand of another way of doing this, I'm happy to hear about it.

Thanks.

**Comment by nsheff** [comment]
You are right, `requireNamespace` is the correct way to do this. In fact, you may even be able to get away with putting those in `Enhances` rather than `Suggests`, if they aren't used in any testing code.

**Comment by rcavalcante** [comment]
There seems to be some weird Travis build stuff happening, but my local checks are fine. I'll go ahead and close this, push it to Bioc, and see what their build system thinks. The change will be included in the next Bioc release.

Again, thanks for the suggestion.
